// PRODUCTS DISPATCH TYPE
export const FETCH_PRODUCTS_REQUEST = "FETCH_PRODUCTS_REQUEST";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAILURE = "FETCH_PRODUCTS_FAILURE";
export const SEARCH_INPUT = "SEARCH_INPUT";
export const SORT_BY_NAME = "SORT_BY_NAME";
export const SORT_BY_PRICE_LOW_TO_HIGH = "SORT_BY_PRICE_LOW_TO_HIGH";
export const SORT_BY_PRICE_HIGH_TO_LOW = "SORT_BY_PRICE_HIGHT_TO_LOW";
export const SORT_BY_RATING_LOW_TO_HIGH = "SORT_BY_RATING_LOW_TO_HIGH";
export const SORT_BY_RATING_HIGH_TO_LOW = "SORT_BY_RATING_HIGH_TO_LOW";
export const SET_PRODUCT_CATEGORY = "SET_PRODUCT_CATEGORY";

// CART DISPATCH TYPE
export const ADD_TO_CART = "ADD_TO_CART";
export const INCREMENT_CART_PRODUCT = "INCREMENT_CART_PRODUCT";
export const DECREMENT_CART_PRODUCT = "DECREMENT_CART_PRODUCT";
export const REMOVE_CART_PRODUCT = "REMOVE_CART_PRODUCT";
export const CLEAR_CART = "CLEAR_CART";
